spring.application.name=edifika-reservation-service
# Servidor
server.port=${PORT:8083}

# DB Supabase (Con los valores por defecto del Session Pooler corregidos)
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://aws-1-us-west-1.pooler.supabase.com:5432/postgres}
spring.datasource.username=${DATABASE_USERNAME:postgres.gacnwbvphegjxviociti}
spring.datasource.password=${DATABASE_PASSWORD:alevarobejacerra}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=false
spring.jpa.hibernate.naming.physical-strategy=com.edifika.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# JWT (Para que Reservations valide la autenticidad de los usuarios)
jwt.secret=${JWT_SECRET:edifika-secret-key-must-be-at-least-32-characters-long}
jwt.expiration.days=${JWT_EXPIRATION_DAYS:365}

# Documentacion
documentation.application.description=@project.description@
documentation.application.version=@project.version@